// Generated by CoffeeScript 1.10.0
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.rando = function(userNumber) {
    var display, randomNumber;
    event.preventDefault();
    userNumber = document.getElementById("userNum").value;
    randomNumber = Math.ceil(Math.random() * 10);
    display = document.getElementById("displayMsg");
    if (!userNumber || isNaN(userNumber)) {
      alert("Please enter a number!");
    } else if (userNumber > 10 || userNumber < 1) {
      alert("Please enter a number between 1-10");
    } else if (userNumber === randomNumber) {
      display.innerHTML = "Good work!";
    } else {
      display.innerHTML = "Not a match ... Guess again!";
      console.log(randomNumber);
    }
    return document.getElementById("form").reset();
  };

}).call(this);
